import {
  AlertCircle,
  ArrowRight,
  BarChart3,
  BrainCircuit,
  Briefcase,
  CheckCircle2,
  DollarSign,
  Loader2,
  TrendingUp,
  Users
} from "lucide-react";
import React, { useEffect, useState } from "react";
import { AnalysisAPI, WorkspaceAnalysis, WorkspaceOverview } from "../services/api/analysis";

const AnalysisView: React.FC = () => {
  const [overview, setOverview] = useState<WorkspaceOverview | null>(null);
  const [workload, setWorkload] = useState<WorkspaceAnalysis | null>(null);
  const [profitability, setProfitability] = useState<WorkspaceAnalysis | null>(null);
  const [loading, setLoading] = useState(true);
  const [analyzingWorkload, setAnalyzingWorkload] = useState(false);
  const [analyzingProfit, setAnalyzingProfit] = useState(false);
  useEffect(() => {
    fetchOverview();
  }, []);

  const fetchOverview = async () => {
    try {
      setLoading(true);
      const data = await AnalysisAPI.getOverview();
      setOverview(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleAnalyzeWorkload = async () => {
    try {
      setAnalyzingWorkload(true);
      const data = await AnalysisAPI.getWorkloadAnalysis();
      setWorkload(data);
    } catch (err) {
      console.error(err);
    } finally {
      setAnalyzingWorkload(false);
    }
  };

  const handleAnalyzeProfitability = async () => {
    try {
      setAnalyzingProfit(true);
      const data = await AnalysisAPI.getProfitabilityAnalysis();
      setProfitability(data);
    } catch (err) {
      console.error(err);
    } finally {
      setAnalyzingProfit(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <Loader2 className="w-12 h-12 text-primary animate-spin" />
        <p className="text-ink-secondary font-medium tracking-wide">Gathering workspace intelligence...</p>
      </div>
    );
  }

  return (
    <div className="p-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <header className="mb-12">
        <div className="flex items-center gap-3 mb-4 opacity-40">
          <BarChart3 className="text-black" size={16} />
          <span className="text-[10px] font-black text-black uppercase tracking-[0.3em]">Workspace Intelligence</span>
        </div>
        <h1 className="text-5xl font-black text-black tracking-tighter leading-tight">
          System Analysis.
        </h1>
        <p className="text-ink-secondary mt-4 max-w-xl text-sm font-medium leading-relaxed">
          Real-time operational overview and high-fidelity strategic signals generated by Lumina.
        </p>
      </header>

      {/* Overview Stats */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
        <StatCard 
          icon={<Briefcase size={20} />} 
          label="Active Projects" 
          value={overview?.counts.projects || 0} 
          trend="+5%"
        />
        <StatCard 
          icon={<Users size={20} />} 
          label="Talent Roster" 
          value={overview?.counts.freelancers || 0} 
          trend="Stable"
        />
        <StatCard 
          icon={<DollarSign size={20} />} 
          label="Total Managed Budget" 
          value={`$${(overview?.financials.totalBudget || 0).toLocaleString()}`} 
          trend="+12%"
        />
        <StatCard 
          icon={<TrendingUp size={20} />} 
          label="Active Assignments" 
          value={overview?.counts.assignments || 0} 
          trend="High"
        />
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Workload Analysis */}
        <div className="glass-panel p-8 rounded-3xl border border-border-subtle hover:border-primary/30 transition-all duration-500">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-indigo-100 rounded-2xl flex items-center justify-center">
                <BrainCircuit className="text-indigo-600" size={24} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-ink-primary leading-tight">Workload Efficiency</h3>
                <p className="text-sm text-ink-tertiary">Global resource utilization</p>
              </div>
            </div>
            {!workload && (
              <button 
                onClick={handleAnalyzeWorkload}
                disabled={analyzingWorkload}
                className="btn-primary px-6 py-2 rounded-xl text-sm font-bold flex items-center gap-2 group"
              >
                {analyzingWorkload ? <Loader2 size={16} className="animate-spin" /> : <BrainCircuit size={16} className="group-hover:rotate-12 transition-transform" />}
                Analyze
              </button>
            )}
          </div>

          {workload ? (
            <AnalysisResults analysis={workload} color="indigo" />
          ) : (
            <div className="h-64 flex flex-col items-center justify-center text-center border-2 border-dashed border-border-subtle rounded-2xl bg-subtle/30">
              <AlertCircle className="text-ink-tertiary mb-3" size={32} />
              <p className="text-ink-secondary text-sm font-medium">No active analysis for workload efficiency.</p>
              <p className="text-ink-tertiary text-xs mt-1">Run AI analysis to detect bottlenecks.</p>
            </div>
          )}
        </div>

        {/* Profitability Analysis */}
        <div className="glass-panel p-8 rounded-3xl border border-border-subtle hover:border-emerald-500/30 transition-all duration-500">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-emerald-100 rounded-2xl flex items-center justify-center">
                <TrendingUp className="text-emerald-600" size={24} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-ink-primary leading-tight">Project Economics</h3>
                <p className="text-sm text-ink-tertiary">Profitability & risk assessment</p>
              </div>
            </div>
            {!profitability && (
              <button 
                onClick={handleAnalyzeProfitability}
                disabled={analyzingProfit}
                className="bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-2 rounded-xl text-sm font-bold flex items-center gap-2 group transition-all"
              >
                {analyzingProfit ? <Loader2 size={16} className="animate-spin" /> : <TrendingUp size={16} className="group-hover:translate-y-[-2px] transition-transform" />}
                Report
              </button>
            )}
          </div>

          {profitability ? (
            <AnalysisResults analysis={profitability} color="emerald" />
          ) : (
            <div className="h-64 flex flex-col items-center justify-center text-center border-2 border-dashed border-border-subtle rounded-2xl bg-subtle/30">
              <AlertCircle className="text-ink-tertiary mb-3" size={32} />
              <p className="text-ink-secondary text-sm font-medium">No active risk report for profitability.</p>
              <p className="text-ink-tertiary text-xs mt-1">Generate a financial status report with Lumina.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

const StatCard: React.FC<{ icon: React.ReactNode; label: string; value: string | number; trend: string }> = ({ icon, label, value, trend }) => (
  <div className="bg-surface p-8 rounded-3xl border border-border-subtle/30 hover:border-border-subtle transition-all duration-300 group">
    <div className="flex items-center justify-between mb-6">
      <div className="text-ink-tertiary group-hover:text-black transition-colors">
        {icon}
      </div>
      <span className="text-[9px] font-black px-2 py-1 bg-subtle text-black rounded-md border border-border-subtle uppercase tracking-widest opacity-60">{trend}</span>
    </div>
    <div className="text-3xl font-black text-black tracking-tighter mb-1">{value}</div>
    <div className="text-[10px] font-black text-ink-tertiary uppercase tracking-[0.2em]">{label}</div>
  </div>
);

const AnalysisResults: React.FC<{ analysis: WorkspaceAnalysis; color: string }> = ({ analysis, color: _color }) => {
  // Color classes available for future styling enhancements
  // const colorClasses = {
  //   indigo: "text-indigo-600 bg-indigo-50 border-indigo-100",
  //   emerald: "text-emerald-600 bg-emerald-50 border-emerald-100"
  // };

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="bg-subtle/50 p-6 rounded-2xl border border-border-subtle/30">
        <p className="text-sm font-medium leading-relaxed text-black">
          {analysis.summary}
        </p>
      </div>
      
      {analysis.sections.map((section, idx) => (
        <div key={idx} className="space-y-4">
          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-ink-tertiary opacity-40">{section.title}</h4>
          <div className="grid grid-cols-1 gap-3">
            {section.insights.map((insight, i) => (
              <div key={i} className="flex items-start gap-4 p-4 bg-surface rounded-2xl border border-border-subtle/30 hover:border-black/10 transition-colors">
                <CheckCircle2 size={14} className="text-black/20 mt-1 shrink-0" />
                <span className="text-sm font-medium text-ink-secondary leading-snug">{insight}</span>
              </div>
            ))}
          </div>
          {section.recommendations.length > 0 && (
            <div className="mt-6 p-6 rounded-2xl bg-black text-white">
              <span className="text-[9px] font-black uppercase tracking-[0.3em] text-white/50 block mb-3">Target Response</span>
              <ul className="space-y-3">
                {section.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-center gap-3 text-xs font-bold leading-tight">
                    <ArrowRight size={12} className="text-white/40" />
                    {rec}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

export default AnalysisView;
