import React from "react";
import DashboardHeader from "../components/dashboard/DashboardHeader";
import HeroProjectCard from "../components/dashboard/HeroProjectCard";
import RecentArtifactsCard, {
  Artifact,
} from "../components/dashboard/RecentArtifactsCard";
import SparkAICard from "../components/dashboard/SparkAICard";
import VibePaletteCard from "../components/dashboard/VibePaletteCard";
import { useDashboardData } from "../hooks/useDashboardData";
import { useToast } from "../hooks/useToast";
import "./DashboardHome.css";

interface DashboardHomeProps {
  onNavigateToGallery?: () => void;
}

const DashboardHome: React.FC<DashboardHomeProps> = ({
  onNavigateToGallery,
}) => {
  const [accentColor, setAccentColor] = React.useState("#2463E6");
  const { toasts, addToast } = useToast();
  const {
    heroProject,
    artifacts,
    loadingHero,
    loadingArtifacts,
    errorHero,
    addArtifact,
  } = useDashboardData();

  // Set CSS custom property for accent color
  React.useEffect(() => {
    document.documentElement.style.setProperty(
      "--dashboard-accent",
      accentColor
    );
    return () => {
      document.documentElement.style.removeProperty("--dashboard-accent");
    };
  }, [accentColor]);

  const handleNotificationsClick = React.useCallback(() => {
    addToast("Notifications panel is coming soon.", "info");
  }, [addToast]);

  const handleNewProjectClick = React.useCallback(() => {
    addToast("New Project modal will open here.", "success");
  }, [addToast]);

  const handleSubmitPrompt = React.useCallback(
    (prompt: string) => {
      const trimmed = prompt.trim();
      if (!trimmed) {
        addToast("Please enter a prompt", "info");
        return;
      }
      if (trimmed.length > 1000) {
        addToast("Prompt is too long (max 1000 characters)", "info");
        return;
      }

      addToast(`Prompt sent: "${trimmed}"`, "success");
      const suffix = trimmed.slice(0, 12);
      const newArtifact = {
        id: `gen-${Date.now()}`,
        name: `${suffix.replace(/\s+/g, "_")}.png`,
        imageSrc: "", // Would be generated by AI in real implementation
      };
      addArtifact(newArtifact);
    },
    [addToast, addArtifact]
  );

  const handleColorSelect = React.useCallback(
    (color: string) => {
      setAccentColor(color);
      addToast(`Accent updated to ${color}`, "info");
    },
    [addToast]
  );

  const handleViewGallery = React.useCallback(() => {
    addToast("Opening gallery...", "info");
    onNavigateToGallery?.();
  }, [addToast, onNavigateToGallery]);

  const handleArtifactClick = React.useCallback(
    (artifact: Artifact) => {
      addToast(`Opening ${artifact.name}`, "info");
    },
    [addToast]
  );

  const accentGlow = React.useMemo(() => `${accentColor}1A`, [accentColor]);
  const containerStyle = React.useMemo(
    (): React.CSSProperties & Record<string, string> => ({
      "--dashboard-accent": accentColor,
      backgroundImage: `radial-gradient(120% 120% at 100% 0%, ${accentGlow}, transparent 40%)`,
    }),
    [accentColor, accentGlow]
  );

  return (
    // eslint-disable-next-line react/forbid-component-props -- dynamic accent color requires inline style
    <main
      className="animate-in fade-in duration-700 pb-32 pt-12 px-12 max-w-[1600px] mx-auto"
      style={containerStyle}
      role="main"
      aria-label="Dashboard home page"
    >
      <div className="fixed top-6 right-6 z-50 space-y-3">
        {toasts.map((toast) => (
          // eslint-disable-next-line react/forbid-component-props -- dynamic accent color
          <div
            key={toast.id}
            className="bg-surface border border-border-subtle rounded-xl shadow-lg px-4 py-3 text-sm text-ink-primary w-72 flex items-start gap-2"
            style={{
              borderColor: toast.type === "success" ? accentColor : undefined,
              boxShadow:
                toast.type === "success"
                  ? "0 10px 30px rgba(36, 99, 230, 0.15)"
                  : undefined,
            }}
            role="status"
            aria-live="polite"
          >
            {/* eslint-disable-next-line react/forbid-component-props -- dynamic accent indicator */}
            <span
              className="mt-1 block w-2 h-2 rounded-full"
              style={{ backgroundColor: accentColor }}
            />
            <span className="flex-1">{toast.message}</span>
          </div>
        ))}
      </div>

      <DashboardHeader
        onNotificationsClick={handleNotificationsClick}
        onNewProjectClick={handleNewProjectClick}
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 auto-rows-min">
        {/* 1. Hero Focus (Large) */}
        {loadingHero ? (
          <div
            className="lg:col-span-6 w-full h-full"
            aria-label="Loading hero project"
          >
            <div className="h-[360px] lg:h-full rounded-2xl bg-subtle border border-border-subtle animate-pulse" />
          </div>
        ) : errorHero ? (
          <div className="lg:col-span-6 w-full h-full flex items-center justify-center">
            <div className="text-center p-8 rounded-2xl bg-error/10 border border-error/20">
              <p className="text-error font-medium mb-2">
                Failed to load project
              </p>
              <p className="text-sm text-error/70">{errorHero}</p>
            </div>
          </div>
        ) : (
          <HeroProjectCard
            imageSrc={heroProject?.imageSrc ?? ""}
            priorityLabel={heroProject?.priorityLabel}
            title={heroProject?.title ?? ""}
            description={heroProject?.description ?? ""}
            className="lg:col-span-6 w-full h-full"
          />
        )}

        {/* Right Column Grid */}
        <div className="lg:col-span-6 grid grid-cols-1 sm:grid-cols-2 gap-6 content-start">
          {/* 2. Spark AI (Ideation) */}
          <SparkAICard
            onSubmitPrompt={handleSubmitPrompt}
            className="sm:col-span-2 lg:col-span-1 min-h-[220px]"
          />

          {/* 3. Vibe / Palette */}
          <VibePaletteCard
            onColorSelect={handleColorSelect}
            className="sm:col-span-2 lg:col-span-1"
            selectedColor={accentColor}
          />

          {/* 4. Artifacts (Visual History) */}
          <RecentArtifactsCard
            artifacts={artifacts}
            loading={loadingArtifacts}
            onViewGallery={handleViewGallery}
            onArtifactClick={handleArtifactClick}
            className="sm:col-span-2"
          />
        </div>
      </div>
    </main>
  );
};

export default DashboardHome;
